
name: Release

on:
  release:
    types: [ created ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Get the version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Setup Altipla tools
      run: go install github.com/altipla-consulting/linter@latest

    - name: Lint
      run: make lint

    - name: Test
      run: make test
